Description of calc2Dist
Home > GVSToolbox > calc2Dist.m
calc2Dist
PURPOSE
Notes: calculates 2-norm distance from target vector to all query vectors
SYNOPSIS
function dist = calc2Dist(target, query)
DESCRIPTION
 Notes: calculates 2-norm distance from target vector to all query vectors
 syntax:  dist = calcEuclidDist( target, query)
 Inputs:
   target: (d by 1) vector of the target vector
   query: (d by N) matrix of the query vectors (dimensionality is d, num
       samples is N )
 Outputs:
   dist: vector of all 2-Norm distances
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
calcAOIFixDensityDist calculate fixation density at the AOIs
calcAOIFixDistHistDist Calculate fixation density for different distances from relevant AOIs
calcAOIFixDurationDist calculate fixation density at the AOIs
calcAOIFixSequenceDist calculate matrix representing the sequence of AOIs fixated
calcAOISacDensityDist calculate target saccade density
calcAOISacSequenceDist calculate matrix representing the sequence of AOIs saccaded to
calcDistTraveled calculate the total distance traveled by the eye
calcLatencyRelAOIFixDist get latency until relevant AOI fixated
calcLatencyRelAOISacDist get latency until relevant AOI is saccade target
codeFixationsDist identify fixations
viewAOILandscape A: image
SOURCE CODE
% Notes: calculates 2-norm distance from target vector to all query vectors
%
% syntax:  dist = calcEuclidDist(target, query)
%
% Inputs:
%   target: (d by 1) vector of the target vector
%   query: (d by N) matrix of the query vectors (dimensionality is d, num
%       samples is N)
%
% Outputs:
%   dist: vector of all 2-Norm distances
function dist = calc2Dist(target, query)
dist = (repmat(target,1,size(query,2)) - query);
dist = sqrt(sum(dist.^2,1));