Description of exampleEasy
Home > GVSToolbox > exampleEasy.m
exampleEasy
PURPOSE
Example for easy use
SYNOPSIS
This is a script file.
DESCRIPTION
 Example for easy use
CROSS-REFERENCE INFORMATION
This function calls:
autoLabel Samuel Rivera
describeVariables This function tells you which variables are best in an easy to understand format
exportToTable This function outputs variables in tab delimited file for further
extractVarsDist extract all variables from a cell of eye tracks
loadFromTable Syntax: dataStruct = loadFromTable(tableFile)
runLDALeave1Out calculate leave 1 subject out accuracy for Bayes classifier with equal covariance
runLRLeave1Out calculate leave 1 subject out accuracy for L1 penalized logistic regression
runSVMLeave1Out calculate leave 1 subject out accuracy for linear SVM
smoothTracks Syntax: dataStruct = smoothTracks(dataStruct)
sortVariablesLR L1 penalized logistic regression ranking of variables
sortVariablesNB Naive bayes ranking of variables (using CV accuracy criterion)
This function is called by:
SOURCE CODE
% Example for easy use
% load up data
dataStruct = loadFromTable('exampleTable.txt');
% smooth and interpolate
dataStruct = smoothTracks(dataStruct);
% extract variables
varParams.imageSize = [1024; 1280]; % set image size (h,width)
varParams.numFixationInSeq = 5;  % keep up to 5 fixations
aoiPositions = [ 20, 40;  % x1, x2
                 40, 80]; % y1, y2
aoiRadius = 30;  % 30 pixel radius for AOI cicular region
relevantAOIs = 1;  % AOI (x1,y1) is relevant AOI
[ featureVect, varParams ] = extractVarsDist(dataStruct.trackCell, aoiPositions, aoiRadius, relevantAOIs, varParams);
% find variables that separate
numWanted = 5;
[ bestVariablesLR ] = sortVariablesLR(featureVect, dataStruct.allLabels, numWanted);
[ bestVariablesBayes] = sortVariablesNB(featureVect, dataStruct.allLabels, ...
                dataStruct.sampsPerSubj, numWanted );
% automatically find labels
labels = autoLabel(featureVect) ;
% output best variables
describeVariables(varParams, bestVariablesLR);
% validate using classifier
[ percCorrectLDA, wLDA ] = runLDALeave1Out(featureVect(bestVariablesLR,:), dataStruct.allLabels, dataStruct.sampsPerSubj);
[ percCorrectLR, wLR ] = runLRLeave1Out(featureVect(bestVariablesLR,:), dataStruct.allLabels, dataStruct.sampsPerSubj);
[ percCorrectSVM, wSVM  ] = runSVMLeave1Out(featureVect(bestVariablesLR,:), dataStruct.allLabels, dataStruct.sampsPerSubj);
% output for analysis
exportToTable(dataStruct, featureVect(bestVariablesLR,:), 'outTemp.txt')