Description of findRedundancies
Home > GVSToolbox > findRedundancies.m
findRedundancies
PURPOSE
finds redundant variables for easy removal
SYNOPSIS
function unqIdx = findRedundancies(featVect)
DESCRIPTION
 finds redundant variables for easy removal
 Feb 25, 2012
 Notes: this funciton checks for redundant variables and returns the index
 of the redundant ones so they can be removed
  inputs:
     featVect:  (numDim x numSample)  matrix
  outputs:
     unqIdx: unique indices
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
sortVariablesANOVA anova ranking of variables
sortVariablesLR L1 penalized logistic regression ranking of variables
sortVariablesNB Naive bayes ranking of variables (using CV accuracy criterion)
SOURCE CODE
% finds redundant variables for easy removal
% Feb 25, 2012
% Notes: this funciton checks for redundant variables and returns the index
% of the redundant ones so they can be removed
%
%  inputs:
%     featVect:  (numDim x numSample)  matrix
%
%  outputs:
%     unqIdx: unique indices
%
function unqIdx = findRedundancies(featVect)
[b  unqIdx ] = unique(featVect, 'first', 'rows');
unqIdx = sort(unqIdx, 'ascend');